server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:lexiconlegal
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

app:
  firm-email: contact@lexiconlegal.com

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate

app:
  firm-email: ${FIRM_EMAIL}
